name: terraform-workflow
# on: 
#   push:
#     branches:
#       - 'main'
#       - 'dev'
on: workflow_dispatch

permissions: 
  id-token: write
  contents: read

jobs:
  terraform-init-plan:
    runs-on: akpool
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.13.1
          
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: e7e76e28-7d96-4d91-9dcc-35550838b76d
          tenant-id: ec84cc3b-8d4d-4362-b666-466802d7ba4e
          subscription-id: 85bce315-2d40-4002-a3d1-b7f28202855c

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: todoapp_infra
      
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: todoapp_infra
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: todoapp_infra
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: todoapp_infra
        
  terraform-apply:
    environment: dev
    needs: terraform-init-plan
    runs-on: akpool
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
          
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: e7e76e28-7d96-4d91-9dcc-35550838b76d
          tenant-id: ec84cc3b-8d4d-4362-b666-466802d7ba4e
          subscription-id: 85bce315-2d40-4002-a3d1-b7f28202855c
      
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: todoapp_infra
        
      - name: terraform-apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: todoapp_infra
    
    
