name: terraform_workflow

on:
  push:
    branches: 
      - 'main'
      - 'features'
      
jobs:
  terraformjob:
    name: 'terraform init'
    runs-on: anmol
    steps:
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
