name: terraform_workflow

on:
  push:
    branches: 
      - 'main'
      - 'features'
      
jobs:
  terraformjob:
    name: 'terraform init'
    runs-on: anmol
    steps:
       - name: Checkout
         uses: actions/checkout@v5.0.0

       - name: Install Terraform
         uses: little-core-labs/install-terraform@v2.0.0
         with:
           version: 4.42.0
           
       - name: Azure Login
         uses: Azure/login@v2.3.0

       - name: Terraform init azurerm backend
         uses: ahmedig/terraform-azurerm-backend@v4
         with:
         azure_credentials: 
         resource_group_name: 'ak-rg'
         container_name: 
         storage_account_name: 
         file_name: # optional, default is terraform.tfstate
         subscription_id: # optional, default is empty
         tf_working_directory: # optional, default is .
           
       - name: Terraform Validation
         uses: tf-actions/validate@v1.0.0
       
        
